### ISSUE TITLE
Performance comparisons or anecdotes?

### ISSUE THREAD

**Issue by dogweather** [Invoca/magic_frozen_string_literal#8]
I'm brainstorming about how to test performance of my apps before and after using the gem with Ruby 2.3. Has anyone done this and would like to share the results?

**Comment by HotFusionMan** [comment]
After upgrading from Ruby 2.2.2 to 2.3.0 and running this gem on our > 2200 file Rails app, our non-Capybara specs run in about 7-8 minutes on Semaphore now rather than about 13 minutes.  The Capybara specs' runtime is essentially unchanged.  We did not bother testing at just the Ruby 2.3.0 upgrade without "# frozen_string_literal: true" applied, so we don't know which of the two factors had the bigger effect.

**Comment by ColinDKelley** [comment]
Mike Perham found 20% reduction of garbage in Sidekiq:
https://www.mikeperham.com/2018/02/28/ruby-optimization-with-one-magic-comment/
We could surmise that garbage collection would run 20% less frequently.
